<?php

namespace App\Services;

use App\Models\ChartOfAccount;
use App\Models\JournalEntry;
use App\Models\JournalEntryLine;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AccountingService
{
    /**
     * Create and post a journal entry automatically.
     */
    public static function createJournalEntry(
        int $companyId,
        string $description,
        array $lines, // [['account_code' => '1110', 'debit' => 100, 'credit' => 0, 'description' => '...'], ...]
        ?string $referenceType = null,
        ?int $referenceId = null
    ): JournalEntry {
        return DB::transaction(function () use ($companyId, $description, $lines, $referenceType, $referenceId) {
            $totalDebit = collect($lines)->sum('debit');
            $totalCredit = collect($lines)->sum('credit');

            if (round($totalDebit, 2) !== round($totalCredit, 2)) {
                throw new \Exception("Journal entry is not balanced. Debit: {$totalDebit}, Credit: {$totalCredit}");
            }

            $entry = JournalEntry::create([
                'company_id' => $companyId,
                'entry_number' => '', // auto-generated by HasAutoNumber trait
                'entry_date' => now()->toDateString(),
                'description' => $description,
                'reference_type' => $referenceType,
                'reference_id' => $referenceId,
                'status' => 'posted',
                'total_debit' => $totalDebit,
                'total_credit' => $totalCredit,
                'created_by' => Auth::id(),
                'posted_at' => now(),
            ]);

            foreach ($lines as $line) {
                $account = ChartOfAccount::where('code', $line['account_code'])->first();

                if (!$account) {
                    throw new \Exception("Account with code [{$line['account_code']}] not found.");
                }

                JournalEntryLine::create([
                    'journal_entry_id' => $entry->id,
                    'account_id' => $account->id,
                    'description' => $line['description'] ?? null,
                    'debit' => $line['debit'] ?? 0,
                    'credit' => $line['credit'] ?? 0,
                ]);
            }

            return $entry;
        });
    }

    /**
     * Post journal for Sales Invoice confirmation
     * Debit: Accounts Receivable (1120)
     * Credit: Sales Revenue (4100)
     * Credit: Tax Payable (2130) - if tax > 0
     */
    public static function postSalesInvoice(\App\Models\SalesInvoice $invoice): void
    {
        $lines = [];

        // Debit AR for total amount
        $lines[] = [
            'account_code' => '1120',
            'debit' => $invoice->total_amount,
            'credit' => 0,
            'description' => "AR for Invoice #{$invoice->invoice_number}",
        ];

        // Credit Sales Revenue (subtotal)
        $lines[] = [
            'account_code' => '4100',
            'debit' => 0,
            'credit' => $invoice->subtotal,
            'description' => "Sales revenue for Invoice #{$invoice->invoice_number}",
        ];

        // Credit Tax Payable if tax exists
        if ($invoice->tax_amount > 0) {
            $lines[] = [
                'account_code' => '2130',
                'debit' => 0,
                'credit' => $invoice->tax_amount,
                'description' => "Tax payable for Invoice #{$invoice->invoice_number}",
            ];
        }

        static::createJournalEntry(
            $invoice->company_id,
            "Sales Invoice #{$invoice->invoice_number} confirmed",
            $lines,
            \App\Models\SalesInvoice::class,
            $invoice->id
        );
    }

    /**
     * Post journal for Purchase Invoice confirmation
     * Debit: Inventory/Expense (1130 or 5100)
     * Debit: Tax (if applicable)
     * Credit: Accounts Payable (2110)
     */
    public static function postPurchaseInvoice(\App\Models\PurchaseInvoice $invoice): void
    {
        $lines = [];

        // Debit Inventory/COGS for subtotal
        $lines[] = [
            'account_code' => '1130',
            'debit' => $invoice->subtotal,
            'credit' => 0,
            'description' => "Inventory for Purchase Invoice #{$invoice->invoice_number}",
        ];

        // Debit Tax if exists
        if ($invoice->tax_amount > 0) {
            $lines[] = [
                'account_code' => '2130',
                'debit' => $invoice->tax_amount,
                'credit' => 0,
                'description' => "Input tax for Purchase Invoice #{$invoice->invoice_number}",
            ];
        }

        // Credit AP for total amount
        $lines[] = [
            'account_code' => '2110',
            'debit' => 0,
            'credit' => $invoice->total_amount,
            'description' => "AP for Purchase Invoice #{$invoice->invoice_number}",
        ];

        static::createJournalEntry(
            $invoice->company_id,
            "Purchase Invoice #{$invoice->invoice_number} confirmed",
            $lines,
            \App\Models\PurchaseInvoice::class,
            $invoice->id
        );
    }

    /**
     * Post journal for Payment
     * Incoming (from customer): Debit Cash/Bank, Credit AR
     * Outgoing (to supplier): Debit AP, Credit Cash/Bank
     */
    public static function postPayment(\App\Models\Payment $payment): void
    {
        $lines = [];

        if ($payment->type === 'incoming') {
            // Debit Cash/Bank
            $lines[] = [
                'account_code' => '1110',
                'debit' => $payment->amount,
                'credit' => 0,
                'description' => "Payment received #{$payment->payment_number}",
            ];
            // Credit AR
            $lines[] = [
                'account_code' => '1120',
                'debit' => 0,
                'credit' => $payment->amount,
                'description' => "AR settlement #{$payment->payment_number}",
            ];
        } else {
            // Debit AP
            $lines[] = [
                'account_code' => '2110',
                'debit' => $payment->amount,
                'credit' => 0,
                'description' => "AP settlement #{$payment->payment_number}",
            ];
            // Credit Cash/Bank
            $lines[] = [
                'account_code' => '1110',
                'debit' => 0,
                'credit' => $payment->amount,
                'description' => "Payment sent #{$payment->payment_number}",
            ];
        }

        static::createJournalEntry(
            $payment->company_id,
            "Payment #{$payment->payment_number} confirmed",
            $lines,
            \App\Models\Payment::class,
            $payment->id
        );
    }
}
